package com.steamyao.newcode.dao;

import com.steamyao.newcode.dataobject.FeedDO;

import java.util.List;

public interface FeedDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    int insert(FeedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    //成功返回1，失败返回0
    int insertSelective(FeedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    FeedDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    int updateByPrimaryKeySelective(FeedDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    int updateByPrimaryKey(FeedDO record);


    //根据 userIds  查询
    List<FeedDO> selectUserFeeds(int maxId, List<Integer> userIds, int count);
}