package com.steamyao.newcode.dao;

import com.steamyao.newcode.dataobject.LoginTicketDO;

public interface LoginTicketDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    int insert(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    int insertSelective(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    LoginTicketDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    int updateByPrimaryKeySelective(LoginTicketDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_ticket
     *
     * @mbg.generated Mon Aug 05 11:37:29 CST 2019
     */
    int updateByPrimaryKey(LoginTicketDO record);


    void updateStatus(String ticket, int status);

    LoginTicketDO selectByTicket(String ticket);
}