package com.steamyao.newcode.dao;

import com.steamyao.newcode.dataobject.MessageDO;

import java.util.List;

public interface MessageDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    int insert(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    int insertSelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    MessageDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    int updateByPrimaryKeySelective(MessageDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table message
     *
     * @mbg.generated Sun Aug 04 10:26:57 CST 2019
     */
    int updateByPrimaryKey(MessageDO record);

    List<MessageDO> getConversationDetail(String conversationId,int offset,int limit);

    List<MessageDO>  getConversationList(int userId, int offset, int limit);

    int  getConversationUnreadCount(int userId,String conversationId);

    void setConversationHasRead(int userId, String conversationId);
}