package com.steamyao.newcode.dao;

import com.steamyao.newcode.dataobject.SortDO;

import java.util.Date;
import java.util.List;

public interface SortDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    int insert(SortDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    int insertSelective(SortDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    SortDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    int updateByPrimaryKeySelective(SortDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sort
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    int updateByPrimaryKey(SortDO record);

    //查询最近更新过的
    List<SortDO> selectSoreDo(int offset, int limit);


    //获取按分数递减的字段
    List<Integer> getSortedList(int offset, int limit);

    //更新评论时间
    void updateCommontTime(int qId, Date updateTime);


}