package com.steamyao.newcode.dataobject;

import java.util.Date;

public class FeedDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.user_id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.type
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.creat_date
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    private Date creatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column feed.data
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    private String data;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.id
     *
     * @return the value of feed.id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.id
     *
     * @param id the value for feed.id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.user_id
     *
     * @return the value of feed.user_id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.user_id
     *
     * @param userId the value for feed.user_id
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.type
     *
     * @return the value of feed.type
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.type
     *
     * @param type the value for feed.type
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.creat_date
     *
     * @return the value of feed.creat_date
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.creat_date
     *
     * @param creatDate the value for feed.creat_date
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column feed.data
     *
     * @return the value of feed.data
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public String getData() {
        return data;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column feed.data
     *
     * @param data the value for feed.data
     *
     * @mbg.generated Fri Aug 09 09:33:36 CST 2019
     */
    public void setData(String data) {
        this.data = data == null ? null : data.trim();
    }
}