package com.steamyao.newcode.dataobject;

import java.util.Date;

public class SortDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.ques_id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Integer quesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.creat_date
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Date creatDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.com_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Integer comCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.update_time
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.score
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Double score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.view_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sort.like_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    private Integer likeCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.id
     *
     * @return the value of sort.id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.id
     *
     * @param id the value for sort.id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.ques_id
     *
     * @return the value of sort.ques_id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Integer getQuesId() {
        return quesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.ques_id
     *
     * @param quesId the value for sort.ques_id
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setQuesId(Integer quesId) {
        this.quesId = quesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.creat_date
     *
     * @return the value of sort.creat_date
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Date getCreatDate() {
        return creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.creat_date
     *
     * @param creatDate the value for sort.creat_date
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setCreatDate(Date creatDate) {
        this.creatDate = creatDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.com_count
     *
     * @return the value of sort.com_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Integer getComCount() {
        return comCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.com_count
     *
     * @param comCount the value for sort.com_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setComCount(Integer comCount) {
        this.comCount = comCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.update_time
     *
     * @return the value of sort.update_time
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.update_time
     *
     * @param updateTime the value for sort.update_time
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.score
     *
     * @return the value of sort.score
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Double getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.score
     *
     * @param score the value for sort.score
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setScore(Double score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.view_count
     *
     * @return the value of sort.view_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.view_count
     *
     * @param viewCount the value for sort.view_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sort.like_count
     *
     * @return the value of sort.like_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sort.like_count
     *
     * @param likeCount the value for sort.like_count
     *
     * @mbg.generated Wed Aug 14 14:25:21 CST 2019
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}